### ISSUE TITLE
SecretBackendRootSignIntermediate ca_chain output 

### ISSUE THREAD

**Issue by shaidar** [pulumi/pulumi-vault#104]
When running `pkisecret.SecretBackendRootSignIntermediate` the `ca_chain` output is returned as `output<string>`
## Expected behavior

The expected behavior is that the `ca_chain` output should be a string value containing the cert chain similar to the output of the `issusing_ca`
## Current behavior
The output for the `ca_chain` is just `output<string>` (string here is not a placeholder and is the exact output)

## Steps to reproduce

Running the following python code against a configured vault backend with a PKI CA to sign cert for the intermediate CA:

```
pki_intermediate_environment_signed_csr= pkisecret.SecretBackendRootSignIntermediate(
            "pki-intermediate-qa-signed-csr",
            backend="pki-ca",
            common_name="pki-intermediate-qa Intermediate Authority",
            csr=self.pki_intermediate_envrionment_cert_request.csr,
        )

export("issuing_ca", pki_intermediate_environment_signed_csr.issuing_ca)
export("ca_chain", pki_intermediate_environment_signed_csr.ca_chain)
```

## Context (Environment)

We are trying to set up vault PKI infrastructure with an offline root CA and an online intermediate CA signing certs for another level of intermediate CA for each one of our projects/environments.

pulumi: `2.22.0`
pulumi_vault: `3.4.1`

**Comment by shaidar** [comment]
Hey @justinvp ! I was just following up on this to see if you've had a chance to take a look at it.

**Comment by shaidar** [comment]
Just checking in on this to see if someone has been able to take a closer look and confirm the issue. Would be great to hear some feedback as it's a current blocker to get vault PKI deployed on our end.

**Comment by joeduffy** [comment]
Just to confirm, `"output<string>"` is shown even _after_ performing the deployment? (That is, confirming the preview, and performing the update.) I ask because it's possible for this to get printed as just an "output" (unknown) during a preview since the value isn't known until after performing the deployment. It could be that `issuing_ca` is known, but `ca_chain` is not, which would explain the difference in output. If this is shown after performing the update, however, we will need to dig further.

**Comment by blarghmatey** [comment]
Hi Joe, thanks for following up. The `output<string>` is the literal value that is returned after executing the state.

**Comment by justinvp** [comment]
I tried the following program connected to a local running vault server in dev mode:

```python
import pulumi
import pulumi_vault as vault

test_root = vault.Mount("test-root",
    type="pki",
    path="pki-root",
    description="test root",
    default_lease_ttl_seconds=8640000,
    max_lease_ttl_seconds=8640000,
)

test_intermediate = vault.Mount("test-intermediate",
    opts=pulumi.ResourceOptions(depends_on=[test_root]),
    type="pki",
    path="pki-intermediate",
    description="test intermediate",
    default_lease_ttl_seconds=86400,
    max_lease_ttl_seconds=86400,
)

test_root_cert = vault.pkisecret.SecretBackendRootCert("test",
    opts=pulumi.ResourceOptions(depends_on=[test_intermediate]),
    backend=test_root.path,
    type="internal",
    common_name="my.domain",
    ttl="86400",
    format="pem",
    private_key_format="der",
    key_type="rsa",
    key_bits=4096,
    ou="test",
    organization="test",
    country="test",
    locality="test",
    province="test",
)

test_intermediate_cert_request = vault.pkisecret.SecretBackendIntermediateCertRequest("test",
    opts=pulumi.ResourceOptions(depends_on=[test_root_cert]),
    backend=test_intermediate.path,
    type="exported",
    common_name="test.my.domain",
)

test_root_sign_intermediate = vault.pkisecret.SecretBackendRootSignIntermediate("test",
    opts=pulumi.ResourceOptions(depends_on=[test_intermediate_cert_request]),
    backend=test_root.path,
    csr=test_intermediate_cert_request.csr,
    common_name="test.my.domain",
    permitted_dns_domains=[".test.my.domain"],
    ou="test",
    organization="test",
    country="test",
    locality="test",
    province="test",
)

pulumi.export("issuing_ca", test_root_sign_intermediate.issuing_ca)
pulumi.export("ca_chain", test_root_sign_intermediate.ca_chain)
```

Interestingly, I'm not seeing the `output<string>` literal for `ca_chain`. Instead, `test_root_sign_intermediate.ca_chain` is an empty string after running `pulumi up` along with the exported stack output value.

This is using `pulumi` CLI v2.22.0 with the `pulumi` 2.22 and `pulumi_vault` 3.4.1 Python SDK packages.

This is likely related to the following upstream bug: https://github.com/hashicorp/terraform-provider-vault/issues/684

**Comment by Ardiea** [comment]
This is no longer an issue as of `5.8.0`. This can probably be closed out. 👍
