### ISSUE TITLE
The provider requires an AWS provider of the same version for the node sdk

### ISSUE THREAD

**Issue by dmattia** [pulumi/pulumi-vault#129]
## Issue details

This module requires the @pulumi/aws provider somehow, seemingly of the same version.

I have a Project that uses both AWS and Vault resources, using the two separate providers. My providers list locally looks like this:
<img width="651" alt="Screen Shot 2021-10-20 at 4 20 22 PM" src="https://user-images.githubusercontent.com/8922077/138174032-c71cdaaa-98a0-4081-aa7d-227c516c6050.png">

When I try to run `pulumi up`, I see that I need the aws provider v4.5.1:

<img width="1018" alt="Screen Shot 2021-10-20 at 4 22 08 PM" src="https://user-images.githubusercontent.com/8922077/138174201-04f9c16d-2106-4c4e-ba98-04978a0350ac.png">

But as you can see in the image above, I want to be using aws provider 4.24.1. If I check the state file, the last deploy used 4.24.1, and in my package.json I explicitly use provider version 4.24.1:

<img width="238" alt="Screen Shot 2021-10-20 at 4 23 03 PM" src="https://user-images.githubusercontent.com/8922077/138174525-eace2234-1a98-4b93-8b7a-68a72ccaea65.png">

In my statefile, the string `4.5.1` never appears, and `4.5.0` only appears in reference to this vault provider:

<img width="259" alt="Screen Shot 2021-10-20 at 4 26 35 PM" src="https://user-images.githubusercontent.com/8922077/138174747-664662d1-5e64-45cf-92b1-5d68125692c8.png">

Running the suggested command, `pulumi plugin install resource aws v4.5.1`, makes everything happy, but I do not understand why this is required, or how this error is generated.

If I change the version of this package from `4.5.1` to `4.5.0`, I see the same error message, but with `4.5.0` instead of `4.5.1`, so the error definitely is related to this package somehow.

### Steps to reproduce

1. Create a Project using both aws and vault resources with different provider versions
2. Try to create resources
3. The version of the @pulumi/vault plugin will be required from the @pulumi/aws provider

Expected: This provider would not change what AWS providers are required
Actual: This package requires a specific AWS provider

**Comment by iwahbe** [comment]
@dmattia Are you still seeing this issue?

**Comment by mikhailshilkov** [comment]
Since we haven't heard back and the issue is quite old, I'll go ahead and close this issue as stale
