### ISSUE TITLE
Use tagged version of pulumi in nodejs sdk

### ISSUE THREAD

**Issue by masterada** [pulumi/pulumi-vault#13]
Yarn issues the following warning after installing this package: `warning Pattern ["@pulumi/pulumi@latest"] is trying to unpack in the same destination "***/.cache/yarn/v4/npm-@pulumi-pulumi-1.6.1-ba3f1026aa92452dee2dadc9388a3c0d41062501/node_modules/@pulumi/pulumi" as pattern ["@pulumi/pulumi@^1.0.0","@pulumi/pulumi@
^1.0.0","@pulumi/pulumi@^1.6.0","@pulumi/pulumi@^1.0.0"]. This could result in non-deterministic behavior, skipping.`

Is it possible to use a tagged version in [package.json](https://github.com/pulumi/pulumi-vault/blob/master/sdk/nodejs/package.json) instead of `@pulumi/pulumi@latest` to avoid issues with it? (I think it doesn't cause an issue currently, but may do so in the future.)

**Comment by pgavlin** [comment]
It is, yes. @stack72 we should update `resouerces.go` to include a reference to a specific version of `@pulumi/pulumi`.
