### ISSUE TITLE
pulumi_vault.Token import is shadowed by token subpackage in Python sdk

### ISSUE THREAD

**Issue by geekofalltrades** [pulumi/pulumi-vault#15]
pulumi_vault.Token cannot be imported:

```
In [1]: import pulumi_vault

In [2]: pulumi_vault.Token
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-5e10c5afb966> in <module>
----> 1 pulumi_vault.Token

AttributeError: module 'pulumi_vault' has no attribute 'Token'
```

I suspect that this is because it resides in [a file called `token.py` in the base package](https://github.com/pulumi/pulumi-vault/blob/v1.4.0/sdk/python/pulumi_vault/token.py), where it is shadowed by [a subpackage also called `token`](https://github.com/pulumi/pulumi-vault/tree/v1.4.0/sdk/python/pulumi_vault/token), but I'm not sure about that; my Python's a little rusty.

**Comment by geekofalltrades** [comment]
Yeah, shadowing is absolutely what's going on. [`__init__.py` has `from .token import *`](https://github.com/pulumi/pulumi-vault/blob/v1.4.0/sdk/python/pulumi_vault/__init__.py#L22), and there's both a module and a package named `token`.

**Comment by geekofalltrades** [comment]
In my virtualenv, I hacked the files manually:

# Moved `token.py` to `token_base.py`.
# Edited `__init__.py` and added `from .token_base import *`.

My pulumi run is working now.

Pick whatever name you like, just needs to be different from the `token` subpackage. I also didn't check if anything aside from `__init__.py` was importing `.token`.

**Comment by stack72** [comment]
Hi @geekofalltrades 

I changed the package to be called TokenAuth - we believed it was fine to make this small breaking change as it was effectively unusable without this change

I am just making the release right now - watch out for v1.5.0

Paul
