### ISSUE TITLE
Refreshing an Identity Group that does not exist causes an error

### ISSUE THREAD

**Issue by CmdrSharp** [pulumi/pulumi-vault#189]
### What happened?

When attempting to refresh an Identity Group that does not exist, it indeed establishes that it can't be found - but instead of removing it from the stack, it errors out.

### Steps to reproduce

- Create an Identity Group via Pulumi
- Delete the Identity Group manually (via Vault GUI or CLI)
- Run `pulumi refresh` or `pulumi up --refresh`

### Expected Behavior

Pulumi should identify that the resources don't exist.

### Actual Behavior

Error:

```
Diagnostics:
  vault:identity:Group (<REDACTED>):
    error: Preview failed: refreshing urn:pulumi:devops::vault-namespace::vault:identity/group:Group::<REDACTED>: 1 error occurred:
    	* error checking if IdentityGroup "<REDACTED>" exists: entity not found: "/identity/group/id/86ab3738-1226-43c0-1c37-22a8c4e38464"

  pulumi:pulumi:Stack (vault-namespace-devops):
    error: preview failed

  vault:identity:Group (<REDACTED>):
    error: Preview failed: refreshing urn:pulumi:devops::vault-namespace::vault:identity/group:Group::<REDACTED>: 1 error occurred:
    	* error checking if IdentityGroup "<REDACTED>" exists: entity not found: "/identity/group/id/4bd58193-d8c4-3384-9b9b-1771cfcdedd5"
```

### Output of `pulumi about`

```
CLI
Version      3.42.0
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown
vault   5.6.0

Host
OS       darwin
Version  12.5
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v18.9.1'

Backend
Name           <REDACTED>
URL            S3 <REDACTED>
User           <REDACTED>
Organizations

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.42.0
@pulumi/vault   5.6.0
@types/node     14.18.31
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
Looks like this was a bug in the upstream provider and has been fixed in v3.9.1: https://github.com/hashicorp/terraform-provider-vault/pull/1567. Should be fixed by https://github.com/pulumi/pulumi-vault/issues/186.
