### ISSUE TITLE
Incorrect default value for max_lease_ttl_seconds setting

### ISSUE THREAD

**Issue by masterada** [pulumi/pulumi-vault#23]
Please set default value for should max_lease_ttl_seconds to 1200 instead of 20:

https://github.com/pulumi/pulumi-vault/blob/66411d0cf7725adfda57d87651735d2fcd6a262f/resources.go#L171

see: https://github.com/terraform-providers/terraform-provider-vault/blob/3eeb5d3c03d7567ae4735df7767516b795ef9b64/vault/provider.go#L136

**Comment by stack72** [comment]
Apolgies @masterada i will make that fix very shortly - that’s my bad of trying to use 20 as the number of minutes :/
