### ISSUE TITLE
Support for bound_claims_type attribute in JWT backend role

### ISSUE THREAD

**Issue by bgagnon** [pulumi/pulumi-vault#84]
Matching issue in the Terraform provider: terraform-providers/terraform-provider-vault#700.

**Comment by justinvp** [comment]
Thanks for pointing this out and linking to the provider issue. We'll keep this open to track on our side.

**Comment by bgagnon** [comment]
Just a heads up -- hashicorp/terraform-provider-vault#700 is fixed upstream.

**Comment by rajiteh** [comment]
FYI the issue is fixed in the terraform provider [v2.17.0 ](https://github.com/hashicorp/terraform-provider-vault/releases/tag/v2.17.0)

**Comment by leezen** [comment]
Fixed via https://github.com/pulumi/pulumi-vault/pull/91
