### ISSUE TITLE
Package needs to be another Version than it is

### ISSUE THREAD

**Issue by TheDome** [pulumi/pulumi-vault#99]
# System info
I am currently using `pulumi v2.20.0` with the `vault 3.4.0` plugin. On ubuntu 20.04 / archlinux (5.10.4-artix2-1)

# Expected behavior
Pulumi should load the plugin v3.4.0 when doing a `pulumi up` or `pulumi preview`

# Current behavior
Pulumi assumes, that it needs to load the plugin v `3.26.1`, which does not exist. The current fix for this seems to be to copy the plugin into a folder stating the required version. 

# Additional info
I am also using the package `aws v3.26.1`. The version requirement seems to change every time I update the aws package. The Resource I have defined from Vault directly accesses data from a generated S3 Bucket to provide a role for Vault. 

Example: 
``` ts

export default class S3BucketConfiguration extends ComponentResource {

 constructor(
    name: string,
    options: S3BucketConfigOpts,
    opts?: ResourceOptions
  ) {
    super('thedome:custom:aws:S3BucketConfig', name, options, opts)

    const defaultOpts: ResourceOptions = { parent: this }
    let bucket = new s3.Bucket(
        name,
        defaultOpts
    )

    const S3AccessPolicy = all([bucket.arn]).apply(([arn]) =>
        JSON.stringify({
          Version: '2012-10-17',
          Statement: [
            { Action: 's3:*', Effect: 'Allow', Resource: [arn, arn + '/*'] }
          ],
        })
    )

    new vault.aws.SecretBackendRole(
      name,
      {
        backend: 'aws',
        credentialType: 'iam_user',
        policyDocument: S3AccessPolicy,
        name: "pulumi.s3." + name
      },
        defaultOpts
    )

 }
}
```

Edit: Adapted code

**Comment by pgavlin** [comment]
> Pulumi assumes, that it needs to load the plugin v 3.26.1, which does not exist.

Just to clarify (given that the AWS plugin _is_ at version 3.26.1): is the CLI trying to load v3.26.1 of the vault plugin?

**Comment by pgavlin** [comment]
Also, do you happen to be using resource options, or is the snippet above exactly the code you're using?

**Comment by TheDome** [comment]
Hi there, 

that's exactly the problem. Currently I have upgraded the AWS package. But the Error message stays the same: 

```
  pulumi:providers:vault (default_3_28_1):
    error: no resource plugin 'vault-v3.28.1' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource vault v3.28.1`

**Comment by TheDome** [comment]
Hi there, 

thank you for taking your time on this issue. Currently I am using a newer version of the `aws` package [3.28.1]. The CI Logs show the same error though: 
```
  pulumi:providers:vault (default_3_28_1):
    error: no resource plugin 'vault-v3.28.1' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource vault v3.28.1`
```
This preview has been made with the plugins 
```
    "@pulumi/aws": "^3.28.1",
    "@pulumi/azure": "^3.46.0",
    "@pulumi/cloudflare": "^2.13.0",
    "@pulumi/cloudinit": "^0.1.2",
    "@pulumi/pagerduty": "^1.3.0",
    "@pulumi/pulumi": "^2.20.0",
    "@pulumi/vault": "^3.4.0",
```
using the NodeJS pulumi framework. Oh the github actions runners. 

Actually I am using the resource options from pulumi making the `BackendRole` a child of my `ComponentResource` . Since I have changes some code (but still receive the error) I have updated my example above. 

Many thanks!

**Comment by TheDome** [comment]
This seems pretty weird, but I removed my copy scripts from my CI after upgrading to `4.0.1` and the issue seems to be resolved. Sadly I'm not able to give any further details except an update of all providers, which resolved the issue. So many thanks anyway!
